import { describe, expect, it } from "vitest"
import { ContextWindowReceivingTracker } from "../ContextWindowReceivingTracker"

function estimateTokens(text: string): number {
	return Math.ceil(Buffer.byteLength(text, "utf8") / 4)
}

describe("ContextWindowReceivingTracker", () => {
	it("estimates text and reasoning from the complete generated byte count instead of rounding every chunk", () => {
		const tracker = new ContextWindowReceivingTracker()

		tracker.apply({ type: "text", text: "a" })
		tracker.apply({ type: "reasoning", reasoning: "b" })
		tracker.apply({ type: "text", text: "c" })
		tracker.apply({ type: "reasoning", reasoning: "d" })

		expect(tracker.getSnapshot()).toMatchObject({
			localEstimatedOutputTokens: 1,
			receivingTokens: 1,
		})
	})

	it("counts only model-generated tool arguments and excludes hosted tool lifecycle payloads", () => {
		const tracker = new ContextWindowReceivingTracker()
		const firstDelta = '{"path":"'
		const secondDelta = 'README.md"}'

		tracker.apply({
			type: "tool_calls",
			function_id: "call_read",
			tool_index: 0,
			tool_call: { function: { name: "read_file", arguments: firstDelta } },
		})
		tracker.apply({
			type: "tool_calls",
			function_id: "call_read",
			tool_index: 0,
			tool_call: { function: { arguments: secondDelta } },
		})
		tracker.apply({
			type: "server_tool",
			function_id: "ws_large_result",
			tool: "WEB_SEARCH" as never,
			phase: "completed",
			result: { results: [{ snippet: "provider result".repeat(4_000) }] },
		})

		expect(tracker.getSnapshot()).toMatchObject({
			localEstimatedOutputTokens: estimateTokens(`${firstDelta}${secondDelta}`),
			receivingTokens: estimateTokens(`${firstDelta}${secondDelta}`),
		})
	})

	it("replaces tool argument deltas with explicit snapshots without double counting duplicate completion payloads", () => {
		const tracker = new ContextWindowReceivingTracker()
		const completeArguments = JSON.stringify({ path: "src/generated.ts", content: "export const value = 1" })
		const splitAt = Math.floor(completeArguments.length / 2)

		tracker.apply({
			type: "tool_calls",
			function_id: "call_write",
			tool_index: 0,
			tool_call: { function: { name: "write_to_file", arguments: completeArguments.slice(0, splitAt) } },
		})
		tracker.apply({
			type: "tool_calls",
			function_id: "call_write",
			tool_index: 0,
			tool_call: { function: { arguments: completeArguments.slice(splitAt) } },
		})
		tracker.apply({
			type: "tool_calls",
			function_id: "call_write",
			tool_index: 0,
			phase: "completed",
			argumentsMode: "snapshot",
			tool_call: { function: { name: "write_to_file", arguments: completeArguments } },
		})
		tracker.apply({
			type: "tool_calls",
			function_id: "call_write",
			tool_index: 0,
			phase: "completed",
			argumentsMode: "snapshot",
			tool_call: { function: { name: "write_to_file", arguments: completeArguments } },
		})

		expect(tracker.getSnapshot()).toMatchObject({
			localEstimatedOutputTokens: estimateTokens(completeArguments),
			receivingTokens: estimateTokens(completeArguments),
		})
	})

	it("lets accumulated Provider output replace the local estimate and exposes authoritative context occupancy", () => {
		const tracker = new ContextWindowReceivingTracker()
		tracker.apply({ type: "text", text: "locally estimated output".repeat(1_000) })

		tracker.apply({
			type: "usage",
			inputTokens: 1_200,
			outputTokens: 800,
			cacheWriteTokens: 300,
			cacheReadTokens: 500,
		})

		expect(tracker.getSnapshot()).toEqual({
			localEstimatedOutputTokens: estimateTokens("locally estimated output".repeat(1_000)),
			providerOutputTokens: 800,
			receivingTokens: 800,
			authoritativeContextTokens: 2_800,
			providerUsage: {
				inputTokens: 1_200,
				outputTokens: 800,
				cacheWriteTokens: 300,
				cacheReadTokens: 500,
			},
		})
	})

	it("shares snapshot and explicit-delta usage semantics with persisted request accounting", () => {
		const tracker = new ContextWindowReceivingTracker()

		tracker.apply({ type: "usage", inputTokens: 1_100, outputTokens: 0 })
		tracker.apply({ type: "usage", usageMode: "delta", inputTokens: 0, outputTokens: 40 })
		tracker.apply({ type: "usage", usageMode: "delta", inputTokens: 0, outputTokens: 60 })
		tracker.apply({ type: "usage", inputTokens: 900, outputTokens: 100 })

		expect(tracker.getSnapshot()).toMatchObject({
			providerOutputTokens: 100,
			receivingTokens: 100,
			authoritativeContextTokens: 1_000,
			providerUsage: {
				inputTokens: 900,
				outputTokens: 100,
				cacheWriteTokens: 0,
				cacheReadTokens: 0,
			},
		})
	})
})
