/**
 * Dline brand mark: one robot, drawn on the 32-unit design grid, and the
 * renderers that place it on every surface.
 *
 * The robot has a forked antenna, chevron ears, a square head and round eyes
 * and a mouth cut out of the head; the approved design is
 * assets/icons/icon-tile.svg. Surfaces differ only in color and background:
 * - tile (Marketplace, README): light robot on a dark tile, the only tiled SVG;
 * - VS Code glyph (activity bar, product icon font, Webview): one theme color;
 * - VS Code panel (editor tab of a Dline panel): transparent, one file per theme;
 * - documentation site (browser tab, header, home page): teal robot on a
 *   transparent background.
 *
 * Every asset is generated by `scripts/generate-brand-icons.mjs` (`npm run icons`).
 */
import { capsule, circle, GRID, generatedNote, roundedRect, toPathData } from "./shapes.mjs"

export { GRID }

const NOTE = generatedNote("scripts/brand/dline-mark.mjs")

const ROBOT = Object.freeze({
	/** Forked antenna: a stem and two branches, drawn as round-capped strokes. */
	antenna: {
		radius: 1.1,
		stem: [
			[16, 10.5],
			[16, 7.5],
		],
		tips: [
			[12.8, 4.5],
			[19.2, 4.5],
		],
	},
	/** Square head: 18 by 18. */
	head: { x: 7, y: 10.5, width: 18, height: 18, radius: 4.5 },
	/** Left chevron ear, top to tip to bottom; the right ear mirrors it. */
	ear: {
		radius: 1.05,
		points: [
			[5.2, 15.5],
			[3.4, 19.5],
			[5.2, 23.5],
		],
	},
	eyes: {
		radius: 2.4,
		centers: [
			[12.3, 18.3],
			[19.7, 18.3],
		],
	},
	mouth: { x: 13, y: 23, width: 6, height: 2.4, radius: 1.2 },
	sleepyEyes: {
		radius: 0.9,
		segments: [
			[
				[10.5, 18.8],
				[14.1, 18.8],
			],
			[
				[17.9, 18.8],
				[21.5, 18.8],
			],
		],
	},
	sleepyMouth: { center: [16, 24.2], radius: 1.1 },
})

/**
 * Browser-tab layout: the same robot with the ears pulled in and the antenna
 * shortened, so the head fills more of a 16 px favicon.
 */
const COMPACT = Object.freeze({
	...ROBOT,
	antenna: {
		...ROBOT.antenna,
		stem: [
			[16, 10.5],
			[16, 8.6],
		],
		tips: [
			[13.9, 6.5],
			[18.1, 6.5],
		],
	},
	ear: {
		...ROBOT.ear,
		points: [
			[5.6, 16.8],
			[4.3, 19.5],
			[5.6, 22.2],
		],
	},
})

const COLORS = Object.freeze({
	/** VS Code tile: dark tile, light robot. */
	tile: "#222222",
	tileRobot: "#F2F2F2",
	/** Editor-tab icon foreground of the dark and light VS Code themes. */
	panelDark: "#C5C5C5",
	panelLight: "#424242",
	/** Documentation site: teal on light backgrounds, a lighter teal on dark ones. */
	webLight: "#1F7A6F",
	webDark: "#5CC8B8",
})

/** The robot is scaled around its center so the tile keeps a margin. */
const TILE = Object.freeze({ radius: 7, margin: 1.25 })

/** Icon-font metrics shared by the glyph and the font header. */
export const FONT = Object.freeze({ unitsPerEm: 1024, ascent: 960, descent: -64, codepoint: 0xe900 })

/**
 * @typedef {import("./shapes.mjs").Point} Point
 * @typedef {"default" | "sleepy"} Expression
 */

/** @param {Point} point @returns {Point} */
function mirror([x, y]) {
	return [GRID - x, y]
}

/**
 * Round-capped strokes along a polyline, one capsule per segment.
 * @param {Point[]} points
 * @param {number} radius
 */
function strokes(points, radius) {
	return points.slice(1).map((point, index) => capsule(points[index], point, radius, true))
}

/**
 * Antenna, ears and head as filled outlines; the face as cut-outs.
 * @param {Expression} [expression]
 * @param {typeof ROBOT} [layout] `COMPACT` for the browser tab.
 * @returns {import("./shapes.mjs").Contour[]}
 */
function markContours(expression = "default", layout = ROBOT) {
	const { antenna, head, ear, eyes, mouth, sleepyEyes, sleepyMouth } = layout
	const [base, fork] = antenna.stem
	const face =
		expression === "sleepy"
			? [
					...sleepyEyes.segments.map(([a, b]) => capsule(a, b, sleepyEyes.radius, false)),
					circle(sleepyMouth.center, sleepyMouth.radius, false),
				]
			: [...eyes.centers.map((center) => circle(center, eyes.radius, false)), roundedRect(mouth, false)]
	return [
		capsule(base, fork, antenna.radius, true),
		...antenna.tips.map((tip) => capsule(fork, tip, antenna.radius, true)),
		...strokes(ear.points, ear.radius),
		...strokes(ear.points.map(mirror), ear.radius),
		roundedRect(head, true),
		...face,
	]
}

/**
 * Outer bounds of the robot silhouette on the design grid.
 * @param {typeof ROBOT} [layout]
 * @returns {{ left: number, top: number, right: number, bottom: number }}
 */
export function markBounds(layout = ROBOT) {
	const { antenna, head, ear } = layout
	const left = Math.min(...ear.points.map(([x]) => x)) - ear.radius
	const top = Math.min(...antenna.tips.map(([, y]) => y)) - antenna.radius
	return { left, right: GRID - left, top, bottom: head.y + head.height }
}

/** Width and height of the head, which carries the icon's proportions. */
export function headSize() {
	return { width: ROBOT.head.width, height: ROBOT.head.height }
}

/**
 * Center of the robot's bounds; every placement scales around this point.
 * @returns {Point}
 */
export function markCenter() {
	const { left, top, right, bottom } = markBounds()
	return [(left + right) / 2, (top + bottom) / 2]
}

/**
 * Robot path on the design grid.
 * @param {Expression} [expression]
 */
export function markPath(expression = "default") {
	return toPathData(markContours(expression))
}

/**
 * Robot path scaled around its center and centered on the grid.
 * @param {number} scale
 */
function centeredPath(scale) {
	const [cx, cy] = markCenter()
	return toPathData(markContours(), { scale, translate: [GRID / 2 - cx * scale, GRID / 2 - cy * scale] })
}

/**
 * Robot scaled to fill the grid, leaving `margin` units on its longer side, and
 * centered on it.
 * @param {typeof ROBOT} [layout] `COMPACT` for the 16 px browser tab.
 * @param {number} [margin]
 */
function filledPath(layout = ROBOT, margin = 0) {
	const { left, top, right, bottom } = markBounds(layout)
	const scale = (GRID - 2 * margin) / Math.max(right - left, bottom - top)
	const [cx, cy] = [(left + right) / 2, (top + bottom) / 2]
	return toPathData(markContours("default", layout), { scale, translate: [GRID / 2 - cx * scale, GRID / 2 - cy * scale] })
}

/** @param {string[]} body @param {string} [attributes] */
function svgDocument(body, attributes = "") {
	return [
		`<svg xmlns="http://www.w3.org/2000/svg" width="${GRID}" height="${GRID}" viewBox="0 0 ${GRID} ${GRID}"${attributes}>`,
		`\t<!-- ${NOTE} -->`,
		...body.map((line) => `\t${line}`),
		"</svg>",
		"",
	].join("\n")
}

/**
 * The icon on a rounded tile; the face is cut out, so it shows the tile. This is
 * the single tiled SVG: another background only needs a different rect fill.
 */
export function tileSvg() {
	return svgDocument([
		`<rect width="${GRID}" height="${GRID}" rx="${TILE.radius}" fill="${COLORS.tile}" />`,
		`<path fill="${COLORS.tileRobot}" d="${filledPath(ROBOT, TILE.margin)}" />`,
	])
}

/** Single-color robot for the activity bar, which uses the SVG as a mask and applies the theme color. */
export function glyphSvg() {
	return svgDocument([`<path fill="currentColor" d="${centeredPath(1)}" />`])
}

/**
 * Editor-tab icon of a Dline panel. VS Code draws it as an image, so it cannot
 * inherit the theme color; each theme gets its own file.
 * @param {"light" | "dark"} theme
 */
export function panelSvg(theme) {
	const color = theme === "dark" ? COLORS.panelDark : COLORS.panelLight
	return svgDocument([`<path fill="${color}" d="${centeredPath(1)}" />`])
}

/** Browser-tab icon of the documentation site: the teal robot on a transparent background. */
export function faviconSvg() {
	return svgDocument([
		`<style>path{fill:${COLORS.webLight}}@media (prefers-color-scheme:dark){path{fill:${COLORS.webDark}}}</style>`,
		`<path d="${filledPath(COMPACT)}" />`,
	])
}

/**
 * Transparent logo for the documentation site header and home page.
 * @param {"light" | "dark"} theme
 */
export function logoSvg(theme) {
	const color = theme === "light" ? COLORS.webLight : COLORS.webDark
	return svgDocument(["<title>Dline</title>", `<path fill="${color}" d="${filledPath()}" />`], ' role="img" aria-label="Dline"')
}

/**
 * Where a design-grid point lands in font units: the robot's center sits in the
 * middle of the em box.
 * @param {Point} point
 * @returns {Point}
 */
export function designToFont([x, y]) {
	const scale = FONT.unitsPerEm / GRID
	const [cx, cy] = markCenter()
	return [FONT.unitsPerEm / 2 + (x - cx) * scale, (FONT.ascent + FONT.descent) / 2 - (y - cy) * scale]
}

/** SVG font holding the single `dline-icon` glyph, the input of svg2ttf. */
export function fontSvg() {
	const scale = FONT.unitsPerEm / GRID
	const glyph = toPathData(markContours(), { scale, translate: designToFont([0, 0]), flipY: true })
	const codepoint = FONT.codepoint.toString(16)
	return [
		'<svg xmlns="http://www.w3.org/2000/svg"><defs>',
		`<font id="dline-icon" horiz-adv-x="${FONT.unitsPerEm}">`,
		`<font-face font-family="dline-icon" units-per-em="${FONT.unitsPerEm}" ascent="${FONT.ascent}" descent="${FONT.descent}" />`,
		`<missing-glyph horiz-adv-x="${FONT.unitsPerEm}" />`,
		`<glyph unicode="&#x${codepoint};" glyph-name="dline" horiz-adv-x="${FONT.unitsPerEm}" d="${glyph}" />`,
		"</font></defs></svg>",
	].join("")
}

/** TypeScript module exposing the Webview's copy of the robot paths. */
export function webviewPathsModule() {
	return [
		`// ${NOTE}`,
		"",
		"/** View box of the Dline mark paths: the 32-unit design grid. */",
		`export const DLINE_MARK_VIEW_BOX = "0 0 ${GRID} ${GRID}"`,
		"",
		// Biome keeps an over-long string initializer on its own indented line.
		"/** The Dline robot; the eyes are cut-outs. */",
		"export const DLINE_MARK_PATH =",
		`\t"${markPath()}"`,
		"",
		"/** The sleepy robot shown in Lazy Teammate Mode. */",
		"export const DLINE_MARK_SLEEPY_PATH =",
		`\t"${markPath("sleepy")}"`,
		"",
	].join("\n")
}
