/**
 * Contour primitives shared by the brand geometries, drawn on a 32-unit design
 * grid with y pointing down.
 *
 * Filled shapes are wound clockwise and cut-outs counter-clockwise, so the
 * nonzero fill rule used by both SVG and TrueType renders the cut-outs as holes.
 */

/** Side of the square design grid. */
export const GRID = 32

/**
 * Header comment for generated files.
 * @param {string} source Geometry module the file is derived from.
 */
export function generatedNote(source) {
	return `Generated by scripts/generate-brand-icons.mjs from ${source}; do not edit.`
}

/**
 * @typedef {[number, number]} Point
 * @typedef {{ type: "M" | "L", to: Point } | { type: "A", to: Point, radius: number, clockwise: boolean }} Command
 * @typedef {Command[]} Contour
 * @typedef {{ x: number, y: number, width: number, height: number, radius: number }} Rect
 */

/**
 * SVG path data for contours placed with a uniform scale, a translation and an
 * optional vertical flip (font coordinates point up).
 * @param {Contour[]} contours
 * @param {{ scale?: number, translate?: Point, flipY?: boolean }} [placement]
 * @returns {string}
 */
export function toPathData(contours, { scale = 1, translate = [0, 0], flipY = false } = {}) {
	/** @param {Point} point */
	const place = ([x, y]) => `${fmt(translate[0] + x * scale)} ${fmt(translate[1] + (flipY ? -y : y) * scale)}`
	/** @param {Command} command */
	const draw = (command) => {
		if (command.type !== "A") {
			return `${command.type}${place(command.to)}`
		}
		const radius = fmt(command.radius * scale)
		// A vertical flip mirrors the turning direction of every arc.
		const sweep = command.clockwise !== flipY ? 1 : 0
		return `A${radius} ${radius} 0 0 ${sweep} ${place(command.to)}`
	}
	return contours.map((contour) => `${contour.map(draw).join("")}Z`).join("")
}

/**
 * Capsule around the segment A→B: the outline of a stroke with round caps.
 * @param {Point} a
 * @param {Point} b
 * @param {number} radius
 * @param {boolean} clockwise
 * @returns {Contour}
 */
export function capsule([ax, ay], [bx, by], radius, clockwise) {
	const length = Math.hypot(bx - ax, by - ay)
	// Normal on the side that makes A+n → B+n → B−n → A−n run clockwise on screen.
	const nx = ((by - ay) / length) * radius
	const ny = ((ax - bx) / length) * radius
	/** @type {Point[]} */
	const [p0, p1, p2, p3] = [
		[ax + nx, ay + ny],
		[bx + nx, by + ny],
		[bx - nx, by - ny],
		[ax - nx, ay - ny],
	]
	return clockwise
		? [move(p0), line(p1), arc(p2, radius, true), line(p3), arc(p0, radius, true)]
		: [move(p0), arc(p3, radius, false), line(p2), arc(p1, radius, false)]
}

/**
 * @param {Rect} rect
 * @param {boolean} clockwise
 * @returns {Contour}
 */
export function roundedRect({ x, y, width, height, radius: r }, clockwise) {
	const [left, top, right, bottom] = [x, y, x + width, y + height]
	return clockwise
		? [
				move([left + r, top]),
				line([right - r, top]),
				arc([right, top + r], r, true),
				line([right, bottom - r]),
				arc([right - r, bottom], r, true),
				line([left + r, bottom]),
				arc([left, bottom - r], r, true),
				line([left, top + r]),
				arc([left + r, top], r, true),
			]
		: [
				move([left + r, top]),
				arc([left, top + r], r, false),
				line([left, bottom - r]),
				arc([left + r, bottom], r, false),
				line([right - r, bottom]),
				arc([right, bottom - r], r, false),
				line([right, top + r]),
				arc([right - r, top], r, false),
			]
}

/**
 * Filled polygon. The points must run clockwise on screen (y down).
 * @param {Point[]} points
 * @returns {Contour}
 */
export function polygon(points) {
	const [first, ...rest] = points
	return [move(first), ...rest.map((point) => line(point))]
}

/**
 * @param {Point} center
 * @param {number} radius
 * @param {boolean} clockwise
 * @returns {Contour}
 */
export function circle([cx, cy], radius, clockwise) {
	return [move([cx - radius, cy]), arc([cx + radius, cy], radius, clockwise), arc([cx - radius, cy], radius, clockwise)]
}

/** @param {Point} to @returns {Command} */
function move(to) {
	return { type: "M", to }
}

/** @param {Point} to @returns {Command} */
function line(to) {
	return { type: "L", to }
}

/** @param {Point} to @param {number} radius @param {boolean} clockwise @returns {Command} */
function arc(to, radius, clockwise) {
	return { type: "A", to, radius, clockwise }
}

/** @param {number} value */
function fmt(value) {
	const rounded = Number(value.toFixed(3))
	return String(Object.is(rounded, -0) ? 0 : rounded)
}
