import { EmptyRequest } from "@shared/proto/dline/common"
import { ApiProfile, ApiProfilesResponse, UpdateApiProfilesRequest } from "@shared/proto/dline/profile"
import PROVIDERS from "@shared/providers/providers.json"
import deepEqual from "fast-deep-equal"
import { useCallback, useEffect, useMemo, useState } from "react"
import { updateSetting, updateTaskSettings } from "@/components/settings/utils/settingsHandlers"
import { FileServiceClient } from "@/services/grpc-client"
import { createEmptyApiProfile, generateApiProfileName } from "./ProviderProfile"

export interface ProfileUpdateResult {
	profiles: ApiProfile[]
	changed: boolean
}

type ProfileMode = "plan" | "act"

let sharedProfiles: ApiProfile[] = []
let sharedLoaded = false
let sharedLoadError: Error | undefined
let sharedLoadPromise: Promise<ApiProfile[]> | undefined
let sharedPersistQueue: Promise<void> = Promise.resolve()
let sharedSelectionQueue: Promise<void> = Promise.resolve()
const profileListeners = new Set<() => void>()

function notifyProfileListeners(): void {
	for (const listener of profileListeners) listener()
}

function replaceSharedProfiles(profiles: ApiProfile[]): void {
	sharedProfiles = profiles
	notifyProfileListeners()
}

function loadSharedProfiles(force = false): Promise<ApiProfile[]> {
	if (sharedLoadPromise && !force) return sharedLoadPromise
	if (sharedLoaded && !force) return Promise.resolve(sharedProfiles)

	const request = FileServiceClient.getApiProfiles({} as EmptyRequest)
		.then((response: ApiProfilesResponse) => {
			sharedProfiles = response.profiles || []
			sharedLoaded = true
			sharedLoadError = undefined
			notifyProfileListeners()
			return sharedProfiles
		})
		.catch((error: unknown) => {
			sharedLoaded = false
			sharedLoadError = error instanceof Error ? error : new Error(String(error))
			notifyProfileListeners()
			throw sharedLoadError
		})
		.finally(() => {
			if (sharedLoadPromise === request) sharedLoadPromise = undefined
		})

	sharedLoadPromise = request
	return request
}

function persistSharedProfiles(profiles: ApiProfile[]): void {
	sharedPersistQueue = sharedPersistQueue
		.catch(() => undefined)
		.then(async () => {
			await FileServiceClient.updateApiProfiles(UpdateApiProfilesRequest.create({ profiles }))
		})
		.catch((error: unknown) => {
			sharedLoadError = error instanceof Error ? error : new Error(String(error))
			notifyProfileListeners()
			void loadSharedProfiles(true).catch(() => undefined)
		})
}

export function applyProfileUpdate(prev: ApiProfile[], id: string, updates: Partial<ApiProfile>): ProfileUpdateResult {
	let changed = false
	const next = prev.map((profile) => {
		if (profile.id !== id) return profile
		const updated = { ...profile, ...updates }
		const isExplicitNameUpdate = "name" in updates
		const isAutoGenerated =
			!updated.name ||
			updated.name === "New Model" ||
			(!isExplicitNameUpdate && updated.provider && updated.name.startsWith(`${updated.provider}:`))
		if (updated.provider && isAutoGenerated) {
			const otherNames = prev.filter((item) => item.id !== id).map((item) => item.name)
			updated.name = generateApiProfileName(updated.provider, updated.modelId || "", otherNames)
		}
		if (deepEqual(updated, profile)) return profile
		changed = true
		return updated
	})

	return { profiles: changed ? next : prev, changed }
}

export function buildProfileSettings(
	profileName: string,
	modes: ProfileMode[],
): { planModeProfile?: string; actModeProfile?: string } {
	return modes.reduce<{ planModeProfile?: string; actModeProfile?: string }>((settings, mode) => {
		if (mode === "plan") settings.planModeProfile = profileName
		else settings.actModeProfile = profileName
		return settings
	}, {})
}

export function shouldUseTaskProfileSettings(taskId: string | undefined, hasActiveTask: boolean): boolean {
	return Boolean(taskId) || hasActiveTask
}

/**
 * Shared ApiProfile store. All hook consumers use one initial RPC and one
 * optimistic profile snapshot, avoiding stale per-component copies.
 */
export function useApiProfiles() {
	const [, forceRender] = useState(0)
	const [expandedId, setExpandedId] = useState<string | null>(null)
	const [editMode, setEditMode] = useState(false)

	useEffect(() => {
		const listener = () => forceRender((value) => value + 1)
		profileListeners.add(listener)
		void loadSharedProfiles().catch(() => undefined)
		return () => {
			profileListeners.delete(listener)
		}
	}, [])

	const persist = useCallback((profiles: ApiProfile[]) => {
		if (!sharedLoaded) return
		replaceSharedProfiles(profiles)
		persistSharedProfiles(profiles)
	}, [])

	const addProfile = useCallback(() => {
		if (!sharedLoaded) return
		const newProfile = createEmptyApiProfile()
		newProfile.name = "New Model"
		persist([...sharedProfiles, newProfile])
		setExpandedId(newProfile.id)
	}, [persist])

	const updateProfile = useCallback(
		(id: string, updates: Partial<ApiProfile>) => {
			const result = applyProfileUpdate(sharedProfiles, id, updates)
			if (result.changed) persist(result.profiles)
		},
		[persist],
	)

	const removeProfile = useCallback(
		(id: string) => {
			persist(sharedProfiles.filter((profile) => profile.id !== id))
			setExpandedId((current) => (current === id ? null : current))
		},
		[persist],
	)

	const toggleEnabled = useCallback(
		(id: string) => {
			persist(sharedProfiles.map((profile) => (profile.id === id ? { ...profile, enabled: !profile.enabled } : profile)))
		},
		[persist],
	)

	const selectProfiles = useCallback((id: string, modes: ProfileMode[], taskId?: string, hasActiveTask = false) => {
		const profile = sharedProfiles.find((item) => item.id === id)
		if (!profile) return Promise.resolve()
		const settings = buildProfileSettings(profile.name || "", modes)
		sharedSelectionQueue = sharedSelectionQueue
			.catch(() => undefined)
			.then(async () => {
				if (shouldUseTaskProfileSettings(taskId, hasActiveTask)) {
					await updateTaskSettings(taskId, settings)
					return
				}
				await Promise.all(
					Object.entries(settings).map(([field, value]) => updateSetting(field as keyof typeof settings, value)),
				)
			})
		return sharedSelectionQueue
	}, [])

	const selectProfile = useCallback(
		(id: string, mode: ProfileMode, taskId?: string, hasActiveTask = false) =>
			selectProfiles(id, [mode], taskId, hasActiveTask),
		[selectProfiles],
	)

	const toggleUsedFor = useCallback(
		(id: string, mode: string) => {
			const profiles = sharedProfiles.map((profile) => {
				if (profile.id !== id) return profile
				const usedFor = profile.usedFor.includes(mode)
					? profile.usedFor.filter((item) => item !== mode)
					: [...profile.usedFor, mode]
				return { ...profile, usedFor }
			})
			persist(profiles)
		},
		[persist],
	)

	const toggleExpand = useCallback((id: string) => {
		setExpandedId((current) => (current === id ? null : id))
	}, [])

	const providerOptions = useMemo(() => PROVIDERS.list, [])

	return {
		profiles: sharedProfiles,
		expandedId,
		setExpandedId,
		editMode,
		setEditMode,
		addProfile,
		updateProfile,
		removeProfile,
		toggleEnabled,
		toggleUsedFor,
		toggleExpand,
		selectProfile,
		selectProfiles,
		providerOptions,
		loaded: sharedLoaded,
		error: sharedLoadError,
		reloadProfiles: () => loadSharedProfiles(true),
	}
}
