import { EmptyRequest } from "@shared/proto/dline/common"
import { ApiProfile, ApiProfilesResponse, UpdateApiProfilesRequest } from "@shared/proto/dline/profile"
import PROVIDERS from "@shared/providers/providers.json"
import deepEqual from "fast-deep-equal"
import { useCallback, useEffect, useMemo, useState } from "react"
import { updateSetting, updateTaskSettings } from "@/components/settings/utils/settingsHandlers"
import { FileServiceClient } from "@/services/grpc-client"
import { createEmptyApiProfile, generateApiProfileName } from "./ProviderProfile"

export interface ProfileUpdateResult {
	profiles: ApiProfile[]
	changed: boolean
}

type ProfileMode = "plan" | "act"

/**
 * Apply a profile update and report whether it changed persisted data.
 *
 * @param prev Existing profile list.
 * @param id Profile id to update.
 * @param updates Partial profile changes.
 * @returns Updated profile list plus a changed flag.
 */
export function applyProfileUpdate(prev: ApiProfile[], id: string, updates: Partial<ApiProfile>): ProfileUpdateResult {
	let changed = false
	const next = prev.map((p) => {
		if (p.id !== id) return p
		const updated = { ...p, ...updates }
		// Auto-generate name when:
		// 1. name is empty (newly created)
		// 2. name is "New Model" (placeholder from addProfile)
		// 3. name looks auto-generated ("provider:xxx") — covers the case
		//    where provider was set first (name = "provider:") and modelId
		//    is added later, or modelId changes.
		const isAutoGenerated =
			!updated.name || updated.name === "New Model" || (updated.provider && updated.name.startsWith(`${updated.provider}:`))
		if (updated.provider && isAutoGenerated) {
			const otherNames = prev.filter((x) => x.id !== id).map((x) => x.name)
			updated.name = generateApiProfileName(updated.provider, updated.modelId || "", otherNames)
		}
		if (deepEqual(updated, p)) {
			return p
		}
		changed = true
		return updated
	})

	return { profiles: changed ? next : prev, changed }
}

/**
 * Build profile settings for one or more mode slots.
 *
 * @param profileName Profile name to select.
 * @param modes Mode slots to update.
 * @returns Partial settings containing the requested profile selections.
 */
export function buildProfileSettings(
	profileName: string,
	modes: ProfileMode[],
): {
	planModeProfile?: string
	actModeProfile?: string
} {
	return modes.reduce<{ planModeProfile?: string; actModeProfile?: string }>((settings, mode) => {
		if (mode === "plan") {
			settings.planModeProfile = profileName
		} else {
			settings.actModeProfile = profileName
		}
		return settings
	}, {})
}

/**
 * Hook for managing configured ApiProfiles.
 * Reads from api_profiles.json via getApiProfiles RPC.
 * Persists via updateApiProfiles RPC.
 *
 * The profile type is the proto-generated ApiProfile from @shared/proto/dline/profile.
 * Each provider's oneof config (profile.anthropic, profile.bedrock, etc.)
 * is accessed directly, NOT wrapped in a providerConfig container.
 */
export function useApiProfiles() {
	const [profiles, setProfiles] = useState<ApiProfile[]>([])
	const [expandedId, setExpandedId] = useState<string | null>(null)
	const [editMode, setEditMode] = useState(false)
	const [loaded, setLoaded] = useState(false)

	// Shared load function so persist can refresh after save
	const loadProfiles = useCallback(() => {
		return FileServiceClient.getApiProfiles({} as EmptyRequest)
			.then((response: ApiProfilesResponse) => {
				setProfiles(response.profiles || [])
				return response.profiles || []
			})
			.catch(() => [])
	}, [])

	// Initialize from RPC — load profiles once on mount, then mark as loaded
	useEffect(() => {
		loadProfiles().then(() => setLoaded(true))
	}, [loadProfiles])

	// Listen for cross-component profile changes — all instances reload
	// on every event since the persist path no longer calls loadProfiles
	// directly (avoiding duplicate RPCs per write).
	useEffect(() => {
		const handler = () => {
			loadProfiles()
		}
		window.addEventListener("profiles-changed", handler)
		return () => window.removeEventListener("profiles-changed", handler)
	}, [loadProfiles])

	// Persist helper — send profiles directly as proto messages, then refresh.
	// CRITICAL: When `loaded` is false the initial data hasn't arrived yet
	// from the backend.  Persisting now — especially from a component whose
	// local profiles array is still [] — would overwrite api_profiles.json
	// with incomplete data, wiping all saved profiles from disk.
	const persist = useCallback(
		(updated: ApiProfile[]) => {
			if (!loaded) {
				console.warn("[useApiProfiles] Skipping persist — data not yet loaded")
				return
			}
			FileServiceClient.updateApiProfiles(UpdateApiProfilesRequest.create({ profiles: updated }))
				.then(() => {
					// Notify all useApiProfiles instances (including self) to reload.
					// A single event-driven reload replaces the previous pattern of
					// direct loadProfiles() + sourced event, which caused duplicate
					// getApiProfiles RPC calls per write.
					window.dispatchEvent(new CustomEvent("profiles-changed"))
				})
				.catch((err) => console.error("Failed to persist ApiProfiles:", err))
		},
		[loaded],
	)

	// Add — auto-generate a default name so the UI never shows an empty name field
	const addProfile = useCallback(() => {
		const newProfile = createEmptyApiProfile()
		// Set a placeholder name; updateProfile will replace it with provider:modelId
		// once the user selects a provider and model.
		newProfile.name = "New Model"
		setProfiles((prev) => {
			const next = [...prev, newProfile]
			persist(next)
			return next
		})
		setExpandedId(newProfile.id)
	}, [persist])

	// Update
	const updateProfile = useCallback(
		(id: string, updates: Partial<ApiProfile>) => {
			setProfiles((prev) => {
				const result = applyProfileUpdate(prev, id, updates)
				if (!result.changed) return prev
				persist(result.profiles)
				return result.profiles
			})
		},
		[persist],
	)

	// Remove
	const removeProfile = useCallback(
		(id: string) => {
			setProfiles((prev) => {
				const next = prev.filter((p) => p.id !== id)
				persist(next)
				return next
			})
			setExpandedId((prev) => (prev === id ? null : prev))
		},
		[persist],
	)

	/**
	 * @deprecated Use selectProfile instead for radio (single-select) behavior.
	 * Toggle enabled status for a single profile.
	 */
	const toggleEnabled = useCallback(
		(id: string) => {
			setProfiles((prev) => {
				const next = prev.map((p) => (p.id === id ? { ...p, enabled: !p.enabled } : p))
				persist(next)
				return next
			})
		},
		[persist],
	)

	/**
	 * Select a single profile for the given mode.
	 * Persists the profile name to planModeProfile or actModeProfile.
	 *
	 * - If taskId is provided: updates task-level settings (only affects that task)
	 * - If taskId is undefined: updates global settings (default for new tasks)
	 *
	 * @param id The profile id to select
	 * @param mode The mode to set the profile for ("plan" or "act")
	 * @param taskId Optional task ID. If provided, updates task-level settings instead of global.
	 */
	const selectProfiles = useCallback(
		(id: string, modes: ProfileMode[], taskId?: string) => {
			const profile = profiles.find((p) => p.id === id)
			if (!profile) return

			const profileName = profile.name || ""
			const settings = buildProfileSettings(profileName, modes)

			if (taskId) {
				updateTaskSettings(taskId, settings)
				return
			}

			for (const [field, value] of Object.entries(settings)) {
				updateSetting(field as keyof typeof settings, value)
			}
		},
		[profiles],
	)

	const selectProfile = useCallback(
		(id: string, mode: ProfileMode, taskId?: string) => {
			selectProfiles(id, [mode], taskId)
		},
		[selectProfiles],
	)

	// Toggle usedFor
	const toggleUsedFor = useCallback(
		(id: string, mode: string) => {
			setProfiles((prev) => {
				const next = prev.map((p) => {
					if (p.id !== id) return p
					const usedFor = p.usedFor.includes(mode) ? p.usedFor.filter((m) => m !== mode) : [...p.usedFor, mode]
					return { ...p, usedFor }
				})
				persist(next)
				return next
			})
		},
		[persist],
	)

	const toggleExpand = useCallback((id: string) => {
		setExpandedId((prev) => (prev === id ? null : id))
	}, [])

	const providerOptions = useMemo(() => PROVIDERS.list, [])

	return {
		profiles,
		expandedId,
		setExpandedId,
		editMode,
		setEditMode,
		addProfile,
		updateProfile,
		removeProfile,
		toggleEnabled,
		toggleUsedFor,
		toggleExpand,
		selectProfile,
		selectProfiles,
		providerOptions,
		loaded,
	}
}
