import { ClineDefaultTool } from "../../../shared/tools"

export const NATIVE_TOOL_IDS = [
	ClineDefaultTool.FILE_NEW,
	ClineDefaultTool.FILE_EDIT,
	ClineDefaultTool.FILE_READ,
	ClineDefaultTool.SEARCH,
	ClineDefaultTool.LIST_FILES,
	ClineDefaultTool.LIST_CODE_DEF,
	ClineDefaultTool.ASK,
	ClineDefaultTool.ATTEMPT,
	ClineDefaultTool.PLAN_MODE,
	ClineDefaultTool.QNA_RESPOND,
	ClineDefaultTool.ACT_MODE,
	ClineDefaultTool.BASH,
	ClineDefaultTool.BROWSER,
	ClineDefaultTool.WEB_FETCH,
	ClineDefaultTool.WEB_SEARCH,
	ClineDefaultTool.MCP_USE,
	ClineDefaultTool.MCP_ACCESS,
	ClineDefaultTool.MCP_DOCS,
	ClineDefaultTool.USE_SKILL,
	ClineDefaultTool.LOAD_MCP,
	ClineDefaultTool.LOAD_SKILL,
	ClineDefaultTool.LOAD_WORKFLOW,
	ClineDefaultTool.FIND_REFERENCES,
	ClineDefaultTool.RENAME,
	ClineDefaultTool.REPLACE_TEXT,
	ClineDefaultTool.APPLY_PATCH,
	ClineDefaultTool.SPAWN_TASK,
	ClineDefaultTool.FOCUS_CHAIN_CHANGE,
	ClineDefaultTool.USE_SUBAGENT,
	ClineDefaultTool.USE_SUBAGENTS,
	ClineDefaultTool.STATUS_UPDATE,
	ClineDefaultTool.GENERATE_EXPLANATION,
	ClineDefaultTool.GENERATE_REPORT,
] as const

export const LITE_TOOL_IDS = [
	ClineDefaultTool.FILE_NEW,
	ClineDefaultTool.FILE_EDIT,
	ClineDefaultTool.FILE_READ,
	ClineDefaultTool.SEARCH,
	ClineDefaultTool.LIST_FILES,
	ClineDefaultTool.LIST_CODE_DEF,
	ClineDefaultTool.ASK,
	ClineDefaultTool.ATTEMPT,
	ClineDefaultTool.PLAN_MODE,
	ClineDefaultTool.QNA_RESPOND,
	ClineDefaultTool.ACT_MODE,
	ClineDefaultTool.BASH,
	ClineDefaultTool.FIND_REFERENCES,
	ClineDefaultTool.RENAME,
	ClineDefaultTool.REPLACE_TEXT,
	ClineDefaultTool.USE_SUBAGENT,
	ClineDefaultTool.USE_SUBAGENTS,
	ClineDefaultTool.SPAWN_TASK,
	ClineDefaultTool.STATUS_UPDATE,
	ClineDefaultTool.GENERATE_REPORT,
] as const
