import type { ClineProviderMetadata } from "@shared/messages/content"
import type { ServerTool } from "@shared/proto/dline/models/metadata"

export type ApiStream = AsyncGenerator<ApiProviderStreamChunk>
export type ApiRawStream = AsyncGenerator<ApiProviderStreamChunk>
export type ApiCanonicalStream = AsyncGenerator<ApiStreamChunk>
export type ApiProviderStreamChunk = ApiStreamChunk | ApiRawStreamToolCallsChunk | ApiRawStreamServerToolChunk
export type ApiRawStreamChunk = ApiProviderStreamChunk
export type ApiStreamChunk =
	| ApiStreamTextChunk
	| ApiStreamThinkingChunk
	| ApiStreamUsageChunk
	| ApiStreamToolCallsChunk
	| ApiStreamServerToolChunk

export interface ApiStreamTextChunk {
	type: "text"
	/**
	 * Text content generated by the model
	 */
	text: string
	provider_metadata?: ClineProviderMetadata
	/**
	 * The thought signature associated with this chunk used by Gemini
	 */
	signature?: string
}

export interface ApiStreamUsageChunk {
	type: "usage"
	inputTokens: number
	outputTokens: number
	cacheWriteTokens?: number
	cacheReadTokens?: number
	thoughtsTokenCount?: number // openrouter
	totalCost?: number // openrouter
	serverToolUsage?: {
		webSearchRequests?: number
	}
	provider_metadata?: ClineProviderMetadata
}

export type ApiServerToolPhase = "started" | "in_progress" | "searching" | "completed" | "failed"

interface ApiServerToolChunkBase {
	type: "server_tool"
	/** Provider-native identity for the hosted invocation. */
	function_id: string
	tool: ServerTool
	phase: ApiServerToolPhase
	input?: unknown
	result?: unknown
	error?: unknown
	provider_metadata?: ClineProviderMetadata
}

export interface ApiRawStreamServerToolChunk extends ApiServerToolChunkBase {
	/** Dline trace identity is assigned by the stream normalizer. */
	dline_tid?: never
}

export interface ApiStreamServerToolChunk extends ApiServerToolChunkBase {
	/** Dline trace identity for the complete hosted lifecycle. */
	dline_tid: string
}

export interface ApiRawStreamToolCallsChunk {
	type: "tool_calls"
	/** Provider-native function call and result pairing identity. */
	function_id: string
	/** Provider-owned replay metadata, never used as runtime identity. */
	provider_metadata?: ClineProviderMetadata
	/** Provider response-local tool position used for interleaved deltas. */
	tool_index?: number
	/** Dline trace identity is absent before canonical normalization. */
	dline_tid?: never
	/**
	 * The tool call information retained during the compatibility migration.
	 */
	tool_call: ApiStreamToolCall
	/** The thought signature associated with this chunk used by Gemini. */
	signature?: string
}

export interface ApiStreamToolCallsChunk {
	type: "tool_calls"
	/** Provider-native function call and result pairing identity. */
	function_id: string
	/** Dline trace identity for the complete tool lifecycle. */
	dline_tid: string
	/** Provider-owned replay metadata, never used as runtime identity. */
	provider_metadata?: ClineProviderMetadata
	/** Provider response-local tool position used for interleaved deltas. */
	tool_index?: number
	/**
	 * The tool call information
	 */
	tool_call: ApiStreamToolCall
	/**
	 * The thought signature associated with this chunk used by Gemini
	 */
	signature?: string
}

export interface ApiStreamToolCall {
	// Information about the tool being called
	function: {
		/**
		 * Name of the tool
		 */
		name?: string
		/**
		 * The arguments passed to the tool execution
		 */
		arguments?: any
	}
}

export interface ApiStreamThinkingChunk {
	type: "reasoning"
	/**
	 * The reasoning text generated by the model.
	 * Redacted reasoning block will have this field set to "[REDACTED]" or an empty string.
	 */
	reasoning: string
	/**
	 * openrouter has various properties that we can pass back unmodified in api requests to preserve reasoning traces
	 * This is also where we store the summary details for OpenAI.
	 */
	details?: unknown
	/**
	 * It's used when sending the thinking block back to the  API.
	 * API expects this in completed form, not as array of deltas.
	 * Also used by Gemini for thought signature associated with this chunk
	 */
	signature?: string
	/**
	 * redacted data
	 */
	redacted_data?: string
	provider_metadata?: ClineProviderMetadata
}
