import type { ClineProviderMetadata } from "@shared/messages/content"
import type { ServerTool } from "@shared/proto/dline/models/metadata"

export type ApiStream = AsyncGenerator<ApiProviderStreamChunk>
export type ApiRawStream = AsyncGenerator<ApiProviderStreamChunk>
export type ApiCanonicalStream = AsyncGenerator<ApiStreamChunk>
export type ApiProviderStreamChunk = ApiStreamChunk | ApiRawStreamToolCallsChunk | ApiRawStreamServerToolChunk
export type ApiRawStreamChunk = ApiProviderStreamChunk
export type ApiStreamChunk =
	| ApiStreamTextChunk
	| ApiStreamThinkingChunk
	| ApiStreamUsageChunk
	| ApiStreamToolCallsChunk
	| ApiStreamServerToolChunk

export interface ApiStreamTextChunk {
	type: "text"
	/**
	 * Text content generated by the model
	 */
	text: string
	provider_metadata?: ClineProviderMetadata
	/**
	 * The thought signature associated with this chunk used by Gemini
	 */
	signature?: string
}

export interface ApiStreamUsageChunk {
	type: "usage"
	/** Usage chunks are Provider snapshots unless an adapter explicitly emits request-local deltas. */
	usageMode?: "snapshot" | "delta"
	/** Non-cache input only; cache read/write fields are disjoint segments of the request context. */
	inputTokens: number
	outputTokens: number
	cacheWriteTokens?: number
	cacheReadTokens?: number
	thoughtsTokenCount?: number // openrouter
	totalCost?: number // openrouter
	serverToolUsage?: {
		webSearchRequests?: number
		webFetchRequests?: number
	}
	provider_metadata?: ClineProviderMetadata
}

export type ApiServerToolPhase = "started" | "in_progress" | "preview" | "searching" | "completed" | "failed"

interface ApiServerToolChunkBase {
	type: "server_tool"
	/** Provider-native identity for the hosted invocation. */
	function_id: string
	tool: ServerTool
	phase: ApiServerToolPhase
	input?: unknown
	result?: unknown
	error?: unknown
	provider_metadata?: ClineProviderMetadata
}

export interface ApiRawStreamServerToolChunk extends ApiServerToolChunkBase {
	/** Dline trace identity is assigned by the stream normalizer. */
	dline_tid?: never
}

export interface ApiStreamServerToolChunk extends ApiServerToolChunkBase {
	/** Dline trace identity for the complete hosted lifecycle. */
	dline_tid: string
}

export type ApiToolCallPhase = "delta" | "completed"
export type ApiToolCallArgumentsMode = "delta" | "snapshot"

export interface ApiRawStreamToolCallsChunk {
	type: "tool_calls"
	/** Provider-native function call and result pairing identity. */
	function_id: string
	/** Provider lifecycle boundary when the adapter can determine it. */
	phase?: ApiToolCallPhase
	/** Tool arguments are streaming deltas unless an adapter explicitly emits complete snapshots. */
	argumentsMode?: ApiToolCallArgumentsMode
	/** Provider-owned replay metadata, never used as runtime identity. */
	provider_metadata?: ClineProviderMetadata
	/** Provider response-local tool position used for interleaved deltas. */
	tool_index?: number
	/** Dline trace identity is absent before canonical normalization. */
	dline_tid?: never
	/**
	 * The tool call information retained during the compatibility migration.
	 */
	tool_call: ApiStreamToolCall
	/** The thought signature associated with this chunk used by Gemini. */
	signature?: string
}

export interface ApiStreamToolCallsChunk {
	type: "tool_calls"
	/** Provider-native function call and result pairing identity. */
	function_id: string
	/** Provider lifecycle boundary when the adapter can determine it. */
	phase?: ApiToolCallPhase
	/** Tool arguments are streaming deltas unless an adapter explicitly emits complete snapshots. */
	argumentsMode?: ApiToolCallArgumentsMode
	/** Dline trace identity for the complete tool lifecycle. */
	dline_tid: string
	/** Provider-owned replay metadata, never used as runtime identity. */
	provider_metadata?: ClineProviderMetadata
	/** Provider response-local tool position used for interleaved deltas. */
	tool_index?: number
	/**
	 * The tool call information
	 */
	tool_call: ApiStreamToolCall
	/**
	 * The thought signature associated with this chunk used by Gemini
	 */
	signature?: string
}

export interface ApiStreamToolCall {
	// Information about the tool being called
	function: {
		/**
		 * Name of the tool
		 */
		name?: string
		/**
		 * The arguments passed to the tool execution
		 */
		arguments?: any
	}
}

export interface ApiStreamThinkingChunk {
	type: "reasoning"
	/**
	 * The reasoning text generated by the model.
	 * Redacted reasoning block will have this field set to "[REDACTED]" or an empty string.
	 */
	reasoning: string
	/**
	 * openrouter has various properties that we can pass back unmodified in api requests to preserve reasoning traces
	 * This is also where we store the summary details for OpenAI.
	 */
	details?: unknown
	/**
	 * It's used when sending the thinking block back to the  API.
	 * API expects this in completed form, not as array of deltas.
	 * Also used by Gemini for thought signature associated with this chunk
	 */
	signature?: string
	/**
	 * redacted data
	 */
	redacted_data?: string
	/**
	 * Whether `redacted_data` is an in-progress snapshot or the provider's authoritative payload.
	 *
	 * Responses reasoning items stream as an in-progress item followed by a completed item, and only
	 * the completed payload may be replayed in a later request. Consumers refresh a `partial`
	 * payload in place per reasoning item and treat `final` as durable.
	 */
	redacted_phase?: "partial" | "final"
	provider_metadata?: ClineProviderMetadata
}
