export type ApiStream = AsyncGenerator<ApiProviderStreamChunk> & { id?: string }
export type ApiRawStream = AsyncGenerator<ApiProviderStreamChunk> & { id?: string }
export type ApiCanonicalStream = AsyncGenerator<ApiStreamChunk> & { id?: string }
export type ApiProviderStreamChunk = ApiStreamChunk | ApiRawStreamToolCallsChunk | ApiLegacyStreamToolCallsChunk
export type ApiRawStreamChunk = ApiProviderStreamChunk
export type ApiStreamChunk = ApiStreamTextChunk | ApiStreamThinkingChunk | ApiStreamUsageChunk | ApiStreamToolCallsChunk

export interface ApiStreamTextChunk {
	type: "text"
	/**
	 * Text content generated by the model
	 */
	text: string
	/**
	 * The response ID associated with this chunk
	 */
	id?: string
	/**
	 * The thought signature associated with this chunk used by Gemini
	 */
	signature?: string
}

export interface ApiStreamUsageChunk {
	type: "usage"
	inputTokens: number
	outputTokens: number
	cacheWriteTokens?: number
	cacheReadTokens?: number
	thoughtsTokenCount?: number // openrouter
	totalCost?: number // openrouter
	/**
	 * The response ID associated with this response
	 */
	id?: string
}

export interface ApiLegacyStreamToolCallsChunk {
	type: "tool_calls"
	function_id?: never
	item_id?: never
	dline_tid?: never
	tool_index?: number
	tool_call: ApiStreamToolCall
	id?: string
	signature?: string
}

export interface ApiRawStreamToolCallsChunk {
	type: "tool_calls"
	/** Provider-native function call and result pairing identity. */
	function_id: string
	/** Provider item identity when the protocol supplies one. */
	item_id?: string
	/** Provider response-local tool position used for interleaved deltas. */
	tool_index?: number
	/** Dline trace identity is absent before canonical normalization. */
	dline_tid?: never
	/**
	 * The tool call information retained during the compatibility migration.
	 */
	tool_call: ApiStreamToolCall
	/** The response ID associated with this chunk. */
	id?: string
	/** The thought signature associated with this chunk used by Gemini. */
	signature?: string
}

export interface ApiStreamToolCallsChunk {
	type: "tool_calls"
	/** Provider-native function call and result pairing identity. */
	function_id: string
	/** Stable logical item identity. */
	item_id: string
	/** Dline trace identity for the complete tool lifecycle. */
	dline_tid: string
	/** Provider response-local tool position used for interleaved deltas. */
	tool_index?: number
	/**
	 * The tool call information
	 */
	tool_call: ApiStreamToolCall
	/**
	 * The response ID associated with this chunk
	 */
	id?: string
	/**
	 * The thought signature associated with this chunk used by Gemini
	 */
	signature?: string
}

export interface ApiStreamToolCall {
	/**
	 * The call ID associated with this tool call
	 */
	call_id?: string
	// Information about the tool being called
	function: {
		/**
		 * The tool call ID
		 */
		id?: string
		/**
		 * Name of the tool
		 */
		name?: string
		/**
		 * The arguments passed to the tool execution
		 */
		arguments?: any
	}
}

export interface ApiStreamThinkingChunk {
	type: "reasoning"
	/**
	 * The reasoning text generated by the model.
	 * Redacted reasoning block will have this field set to "[REDACTED]" or an empty string.
	 */
	reasoning: string
	/**
	 * openrouter has various properties that we can pass back unmodified in api requests to preserve reasoning traces
	 * This is also where we store the summary details for OpenAI.
	 */
	details?: unknown
	/**
	 * It's used when sending the thinking block back to the  API.
	 * API expects this in completed form, not as array of deltas.
	 * Also used by Gemini for thought signature associated with this chunk
	 */
	signature?: string
	/**
	 * redacted data
	 */
	redacted_data?: string
	/**
	 * The response ID associated with this chunk
	 */
	id?: string
}
